apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agentic-patching-llsd-files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
